### ISSUE TITLE
Maelstrom....again

### ISSUE THREAD

**Issue by waffleboy81** [TekNoLogic/GoodNewsEveryone#18]
I realize the Maelstrom Weapon issue has been addressed a few times already, but mine's still producing an error when I get to 5 stacks.

Message: ...terface\AddOns\goodnewseveryone\GoodNewsEveryone.lua:218: attempt to concatenate local 'icon' (a nil value)
Time: 01/29/10 13:56:21
Count: 2
Stack: [C]: ?
...terface\AddOns\goodnewseveryone\GoodNewsEveryone.lua:218: in function <...terface\AddOns\goodnewseveryone\GoodNewsEveryone.lua:211>
(tail call): ?

Locals: 

And that's the entirety of what it outputs. I've made sure I'm at v3.2.0.5, I've implemented any changes I could find on here which were pertinent, and the error stays the same. :(

**Comment by tekkub** [comment]
Closing as stale.  Please reopen if this is still an issue.
